<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php $isSecure = Mage::app()->getStore()->isCurrentlySecure(); ?>
<?php $URL_SITE = Mage::getBaseUrl('web', $isSecure) ?>
<?php $_shipment = $this->getShipment() ?>
<?php $_order = $this->getOrder() ?>
<br />
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>

    <?php $i = 0;
    foreach ($_shipment->getAllTracks() as $_item): $i++
        ?>

        <?php if (strtolower($this->escapeHtml($_item->getTitle())) != 'servientrega') {
            ?>
            <p>El Producto se ha enviado desde las instalaciones del fabricante en Asia a través de <b><?php echo $this->escapeHtml($_item->getTitle()) ?></b></p>
            <p>Puedes rastrear el envio desde el Panel de Usuario de DT-Store - <a href="<?php echo $URL_SITE ?>/sales/order/view/order_id/<?php echo $_order->getId() ?>/" target="_blank">Rastrear Envio Aqui</a></p>
            <?php
        } else {
            ?>
            <p>El producto se encuentra actualmente en Colombia y ha sido enviado a través de <b><?php echo $this->escapeHtml($_item->getTitle()) ?>. </b></p> 
            <p>Puedes rastrear el envio desde el Panel de Usuario de DT-Store - <a href="<?php echo $URL_SITE ?>/sales/order/view/order_id/<?php echo $_order->getId() ?>/" target="_blank">Rastrear Envio Aqui</a></p>
            <?php
        }
        ?>


        <br />

    <?php endforeach ?>

<?php endif; ?>

