<?php
/* * ****************************************************
 * Website: http://www.plazathemes.com
 * ***************************************************** */
?> 
<?php if ($this->getConfig('enabled')) { ?>	  <!-- start enable -->
    <?php $cur_store = Mage::app()->getStore()->getId() ?>
    <script type="text/javascript" src="/jssor/js/jssor.js"></script>
    <script type="text/javascript" src="/jssor/js/jssor.slider.js"></script>


    <script>
                jQuery(document).ready(function ($) {
        //Reference http://www.jssor.com/development/slider-with-slideshow-jquery.html
        //Reference http://www.jssor.com/development/tool-slideshow-transition-viewer.html

        var _SlideshowTransitions = [
                //Return TB
                { $Duration: 1200, y: - 1, $Easing: { $Top: $JssorEasing$.$EaseInOutQuart, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2, $ZIndex: - 10, $Brother: { $Duration: 1200, y: - 1, $Easing: { $Top: $JssorEasing$.$EaseInOutQuart, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2, $ZIndex: - 10, $Shift: - 100 } },
        ];
                var _CaptionTransitions = [

                        //ZMS|B
                        {$Duration: 700, y: - 0.6, $Zoom: 1, $Easing: { $Top: $JssorEasing$.$EaseInCubic, $Zoom: $JssorEasing$.$EaseInCubic }, $Opacity: 2 },
                ];
                var options = {
                $AutoPlay: true, //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                        $AutoPlaySteps: 1, //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                        $AutoPlayInterval: 4000, //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                        $PauseOnHover: 1, //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                        $ArrowKeyNavigation: true, //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                        $SlideDuration: 500, //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                        $MinDragOffsetToSlide: 20, //[Optional] Minimum drag offset to trigger slide , default value is 20
                        //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                        //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                        $SlideSpacing: 0, //[Optional] Space between each slide in pixels, default value is 0
                        $DisplayPieces: 1, //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                        $ParkingPosition: 0, //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                        $UISearchMode: 1, //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                        $PlayOrientation: 1, //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                        $DragOrientation: 3, //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

                        $SlideshowOptions: {                                //[Optional] Options to specify and enable slideshow or not
                        $Class: $JssorSlideshowRunner$, //[Required] Class to create instance of slideshow
                                $Transitions: _SlideshowTransitions, //[Required] An array of slideshow transitions to play slideshow
                                $TransitionsOrder: 1, //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
                                $ShowLink: true                                    //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
                        },
                        $CaptionSliderOptions: {                            //[Optional] Options which specifies how to animate caption
                        $Class: $JssorCaptionSlider$, //[Required] Class to create instance to animate caption
                                $CaptionTransitions: _CaptionTransitions, //[Required] An array of caption transitions to play caption, see caption transition section at jssor slideshow transition builder
                                $PlayInMode: 1, //[Optional] 0 None (no play), 1 Chain (goes after main slide), 3 Chain Flatten (goes after main slide and flatten all caption animations), default value is 1
                                $PlayOutMode: 3                                 //[Optional] 0 None (no play), 1 Chain (goes before main slide), 3 Chain Flatten (goes before main slide and flatten all caption animations), default value is 1
                        },
                        $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not
                        $Class: $JssorBulletNavigator$, //[Required] Class to create navigator instance
                                $ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
                                $AutoCenter: 0, //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                                $Steps: 1, //[Optional] Steps to go for each navigation request, default value is 1
                                $Lanes: 1, //[Optional] Specify lanes to arrange items, default value is 1
                                $SpacingX: 10, //[Optional] Horizontal space between each item in pixel, default value is 0
                                $SpacingY: 10, //[Optional] Vertical space between each item in pixel, default value is 0
                                $Orientation: 1                                 //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
                        },
                        $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$, //[Requried] Class to create arrow navigator instance
                                $ChanceToShow: 2                                //[Required] 0 Never, 1 Mouse Over, 2 Always
                        }
                };
                var jssor_slider1 = new $JssorSlider$("slider1_container", options);
                var jssor_slider2 = new $JssorSlider$("slider2_container", options);
                //responsive code begin
                        //you can remove responsive code if you don't want the slider scales while window resizes
                                function ScaleSlider() {
                                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                                        if (parentWidth){
                                jssor_slider1.$ScaleWidth(Math.min(parentWidth, 840));
                                        jssor_slider2.$ScaleWidth(Math.min(parentWidth, 840));
                                }
                                else{
                                window.setTimeout(ScaleSlider, 30);
                                }
                                }
                        ScaleSlider();
                                $(window).bind("load", ScaleSlider);
                                $(window).bind("resize", ScaleSlider);
                                $(window).bind("orientationchange", ScaleSlider);
                                //responsive code end
                        });</script>

    <?php
    $sql = 'SELECT * FROM  banners_nikolai_bannerdt as b WHERE  status = 1 and seccion = 1 order by ordenamiento ASC';
// fetch write database connection that is used in Mage_Core module
    $write = Mage::getSingleton('core/resource')->getConnection('core_write');

// now $write is an instance of Zend_Db_Adapter_Abstract
    $result = $write->query($sql);

    //var_dump(count($result->fetchAll()));

    $resultQuery = $result->fetchAll();


    if (count($resultQuery) > 0) {
        ?>
        <!-- Jssor Slider Begin -->
        <!-- You can move inline styles to css file or css block. -->
        <div id="slider1_container" style="position: relative; width: 840px;height: 250px; overflow: hidden;">

            <!-- Loading Screen -->
            <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                     background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
                </div>
                <div style="position: absolute; display: block; background: url(/jssor/img/loading.gif) no-repeat center center;
                     top: 0px; left: 0px;width: 100%;height:100%;">
                </div>
            </div>

            <!-- Slides Container -->
            <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 840px; height: 250px;
                 overflow: hidden;">
                 <?php
                 foreach ($resultQuery as $images) {
                     ?>
                    <div>
                        <a u=image href="<?php echo isset($images['enlace'])?'http://'.$images['enlace']:'#'; ?>" onclick="<?php echo $images['onclick']; ?>"><img src="/media/bannerdt/image/<?php echo $images['image']; ?>" /></a>

                    </div>
                <?php }
                ?>

            </div>

            <!-- bullet navigator container -->
            <div u="navigator" class="jssorb01" style="position: absolute; bottom: 16px; right: 10px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype" style="POSITION: absolute; WIDTH: 12px; HEIGHT: 12px;"></div>
            </div>
            <!-- Bullet Navigator Skin End -->


            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora05l" style="width: 40px; height: 40px; top: 113px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora05r" style="width: 40px; height: 40px; top: 113px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->

        </div>

        <?php
    }
    ?>



    <?php
    $sql = 'SELECT * FROM  banners_nikolai_bannerdt as b WHERE  status = 1 and seccion = 2 order by ordenamiento ASC';
// fetch write database connection that is used in Mage_Core module
    $write = Mage::getSingleton('core/resource')->getConnection('core_write');

// now $write is an instance of Zend_Db_Adapter_Abstract
    $result = $write->query($sql);


    //var_dump(count($result->fetchAll()));

    $resultQuery = $result->fetchAll();


    if (count($resultQuery) > 0) {
        ?>


        <div id="slider2_container" style="position: relative; width: 840px;height: 150px; overflow: hidden;float:left;margin-top: 15px;margin-bottom: 15px;">

            <!-- Loading Screen -->
            <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                     background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
                </div>
                <div style="position: absolute; display: block; background: url(/jssor/img/loading.gif) no-repeat center center;
                     top: 0px; left: 0px;width: 100%;height:100%;">
                </div>
            </div>

            <!-- Slides Container -->
            <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 840px; height: 150px;
                 overflow: hidden;">


                <?php
                foreach ($resultQuery as $images) {
                    ?>
                    <div>
                        <a u=image href="<?php echo isset($images['enlace'])?'http://'.$images['enlace']:'#'; ?>" onclick="<?php echo $images['onclick']; ?>"><img src="/media/bannerdt/image/<?php echo $images['image']; ?>" /></a>

                    </div>
                <?php }
                ?>
            </div>

            <!-- bullet navigator container -->
            <div u="navigator" class="jssorb01" style="position: absolute; bottom: 16px; right: 10px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype" style="POSITION: absolute; WIDTH: 12px; HEIGHT: 12px;"></div>
            </div>
            <!-- Bullet Navigator Skin End -->


            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora05l" style="width: 40px; height: 40px; top: 53px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora05r" style="width: 40px; height: 40px; top: 53px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->

        </div>

        <?php
    }
    ?>






    <!-- Bullet Navigator Skin Begin -->
    <!-- jssor slider bullet navigator skin 01 -->
    <style>
        /*
        .jssorb01 div           (normal)
        .jssorb01 div:hover     (normal mouseover)
        .jssorb01 .av           (active)
        .jssorb01 .av:hover     (active mouseover)
        .jssorb01 .dn           (mousedown)
        */
        .jssorb01 div, .jssorb01 div:hover, .jssorb01 .av
        {
            filter: alpha(opacity=70);
            opacity: .7;
            overflow:hidden;
            cursor: pointer;
            border: #000 1px solid;
        }
        .jssorb01 div { background-color: gray; }
        .jssorb01 div:hover, .jssorb01 .av:hover { background-color: #d3d3d3; }
        .jssorb01 .av { background-color: #fff; }
        .jssorb01 .dn, .jssorb01 .dn:hover { background-color: #555555; }
    </style>
    <!-- Arrow Navigator Skin Begin -->
    <style>
        /* jssor slider arrow navigator skin 05 css */
        /*
        .jssora05l              (normal)
        .jssora05r              (normal)
        .jssora05l:hover        (normal mouseover)
        .jssora05r:hover        (normal mouseover)
        .jssora05ldn            (mousedown)
        .jssora05rdn            (mousedown)
        */
        .jssora05l, .jssora05r, .jssora05ldn, .jssora05rdn
        {
            position: absolute;
            cursor: pointer;
            display: block;
            background: url(/jssor/img/a17.png) no-repeat;
            overflow:hidden;
        }
        .jssora05l { background-position: -10px -40px; }
        .jssora05r { background-position: -70px -40px; }
        .jssora05l:hover { background-position: -130px -40px; }
        .jssora05r:hover { background-position: -190px -40px; }
        .jssora05ldn { background-position: -250px -40px; }
        .jssora05rdn { background-position: -310px -40px; }

        @media(max-width: 900px){
            #slider1_container, #slider2_container{
                display: none;
            }
        }

    </style>

    <div class="ma-banner7-container">
        <!--<div class="container">-->
        <div class="flexslider ma-nivoslider">
            <div class="ma-loading"></div>
            <div id="ma-inivoslider" class="slides">

                <?php
                // Get data banner
                $slide = $this->getDataBanner7();
                $path = Mage::getBaseUrl('media');
                $qty_Item = $this->getConfig('qty_item');
                if ($this->getConfig('auto')) {
                    $auto = 'true';
                } else {
                    $auto = 'false';
                }
                /* Get max item & qty item */
                if ($qty_Item > count($slide)) {
                    $qty_Item = count($slide);
                }
                ?>
                <?php
                $i = 1;
                foreach ($slide as $s) {
                    if ($i <= $qty_Item) {
                        //Get images slide show
                        $st1 = $s['image'];
                        $p1 = strpos($st1, 'banner7');
                        $st2 = substr($st1, $p1 + 7);
                        $p2 = strpos($st2, '"');
                        $imag = substr($st2, 0, $p2);
                        ?>
                        <img style="display: none;" src="<?php echo $path . 'magentothem/banner7' . $imag; ?>" alt="" title="#banner7-caption<?php echo $i; ?>"  />
                        <?php $i++; ?>
                        <?php
                    }//end if
                } // end foreach
                ?>
            </div>
            <?php if ($this->getConfig('description')) { ?>
                <?php
                $i = 1;
                foreach ($slide as $s) {
                    ?>

                    <div id="banner7-caption<?php echo $i; ?>" class="banner7-caption nivo-html-caption nivo-caption">
                        <div class="banner7-title">
                            <h3><?php echo $this->__($s['title']) ?></h3>
                        </div>
                        <div class="banner7-des">
                            <?php echo $this->__($s['description']) ?>
                        </div>
                        <?php if ($s['link']) { ?>
                            <div class="banner7-readmore">
                                <a href="<?php echo $s['link'] ?>" title="<?php echo $this->__('Read more') ?>"><?php echo $this->__('Read more') ?></a>	
                            </div>
                        <?php } ?>
                    </div>						
                    <?php
                    $i++;
                }
            }
            ?>
            <script type="text/javascript">
                        $jq(window).load(function() {
                $jq('#ma-inivoslider').nivoSlider({
                effect: '<?php echo $this->getConfig('animation') ?>',
                        slices: 15,
                        boxCols: 8,
                        boxRows: 4,
                        animSpeed: <?php echo $this->getConfig('interval') ?>,
                        pauseTime: <?php echo $this->getConfig('speed') ?>,
                        startSlide: 0,
    <?php if (!$this->getConfig('nav_ctrl')) { ?>
                    controlNav: false,
    <?php } ?>
    <?php if (!$this->getConfig('next_back')) { ?>
                    directionNav: false,
    <?php } ?>
                controlNavThumbs: false,
                        pauseOnHover: true,
                        manualAdvance: false,
                        prevText: 'Prev',
                        nextText: 'Next',
                        afterLoad: function(){
                        $jq('.ma-loading').css("display", "none");
                                //$jq('.banner7-title, .banner7-des, .banner7-readmore').css("left","100px") ;
                        },
                        beforeChange: function(){
                        $jq('.banner7-title, .banner7-des').css("left", "-2000px");
                                $jq('.banner7-readmore').css("left", "-2000px");
                        },
                        afterChange: function(){
                        $jq('.banner7-title, .banner7-des, .banner7-readmore').css("left", "40px")
                        }
                });
                });
            </script>
        </div>
        <!--</div>-->
    </div>
<?php } ?> <!-- end enable -->