<?php
/**
 * Amazon_Products extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Amazon
 * @package        Amazon_Products
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Amazon Product list template on product page
 *
 * @category    Amazon
 * @package     Amazon_Products
 * @author      Ultimate Module Creator
 */
?>
<?php $amazons = $this->getAmazonCollection();?>
<?php if ($amazons && $amazons->count() > 0) :?>
<div class="box-collateral box-amazons box-up-sell">
    <?php foreach ($amazons as $_amazon) : ?>
        <div class="item">
            <?php echo $_amazon->getName();?>
<br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
