<?php
/**
 * amazonProducts_AmazonProducts extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       amazonProducts
 * @package        amazonProducts_AmazonProducts
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Amazon Product list template on product page
 *
 * @category    amazonProducts
 * @package     amazonProducts_AmazonProducts
 * @author      Ultimate Module Creator
 */
?>
<?php $amazonproducts = $this->getAmazonproductCollection();?>
<?php if ($amazonproducts && $amazonproducts->count() > 0) :?>
<div class="box-collateral box-amazonproducts box-up-sell">
    <?php foreach ($amazonproducts as $_amazonproduct) : ?>
        <div class="item">
            <?php echo $_amazonproduct->getName();?>
<br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
